workspace:
  base: /go
  path: src/github.com/lunny/tango

clone:
  git:
    image: plugins/git:next
    depth: 50
    tags: true

pipeline:

  test:
    image: golang:1.8
    group: testing
    pull: true
    commands:
      - go get -t -d -v ./...
      - go build -v
      - go test -v -race -coverprofile=coverage.txt -covermode=atomic
    when:
      event: [ push, pull_request ]

  coverage:
    image: plugins/codecov
    secrets: [ codecov_token ]
    files:
      - coverage.txt
    when:
      event: [ push, pull_request ]

  test:
    image: golang:1.9
    group: testing
    pull: true
    commands:
      - go get -t -d -v ./...
      - go build -v
    when:
      event: [ push, pull_request ]

  test:
    image: golang:1.10
    group: testing
    pull: true
    commands:
      - go get -t -d -v ./...
      - go build -v
    when:
      event: [ push, pull_request ]

  test:
    image: golang:1.11
    group: testing
    pull: true
    commands:
      - go get -t -d -v ./...
      - go build -v
    when:
      event: [ push, pull_request ]